# Spam Base dataset training

In [34]:
from sklearn.metrics import roc_auc_score,confusion_matrix,precision_score,recall_score,accuracy_score
from sklearn.svm import SVC
import pandas as pd
import numpy as np

data_file = open('../datasets/spambase/spambase.data')

columns = ["word_freq_make", "word_freq_address", "word_freq_all", "word_freq_3d", "word_freq_our", "word_freq_over", "word_freq_remove", "word_freq_internet", "word_freq_order", "word_freq_mail", "word_freq_receive", "word_freq_will", "word_freq_people", "word_freq_report", "word_freq_addresses", "word_freq_free", "word_freq_business", "word_freq_email", "word_freq_you", "word_freq_credit", "word_freq_your", "word_freq_font", "word_freq_000", "word_freq_money", "word_freq_hp", "word_freq_hpl", "word_freq_george", "word_freq_650", "word_freq_lab", "word_freq_labs", "word_freq_telnet", "word_freq_857", "word_freq_data", "word_freq_415", "word_freq_85", "word_freq_technology", "word_freq_1999", "word_freq_parts", "word_freq_pm", "word_freq_direct", "word_freq_cs", "word_freq_meeting", "word_freq_original", "word_freq_project", "word_freq_re", "word_freq_edu", "word_freq_table", "word_freq_conference", "char_freq_;", "char_freq_(", "char_freq_[", "char_freq_!", "char_freq_$", "char_freq_#", "capital_run_length_average", "capital_run_length_longest", "capital_run_length_total", "class"]
df = pd.DataFrame(columns=columns)

i = 0
for line in data_file:
    df.loc[i] = [float(val) for val in line.split(',')]
    i += 1

print(df.shape)
df.head()

(4601, 58)


word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0.00            0.00  ...         0.00        0.000   
1             0.00            0.94  ...         0.00        0.132   
2             0.64            0.25  ...         0.01        0.143   
3             0.31            0.63  ...         0.00        0.137   
4             0.31            0.63  ...         0.00        0.135   

   char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0          0.0        0.778        0.000        0.000   
1          0.0        0.372        0.180        0.048   
2          0.0        0.276        0.184        0.010   
3          0.0        0.137        0.000        0.000   
4          0.0        0.135        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                        61.0   
1                       5.114                       101.0   
2                       9.821                       485.0   
3                       3.537                        40.0   
4                       3.537                        40.0   

   capital_run_length_total  class  
0                     278.0    1.0  
1                    1028.0    1.0  
2                    2259.0    1.0  
3                     191.0    1.0  
4                     191.0    1.0  

[5 rows x 58 columns]

In [ ]:
df.info()

In [30]:
dataset = df.values

np.random.shuffle(dataset)
X = dataset[:,:-1]
Y = dataset[:,-1]
Y= Y.astype('int32')
print(X)
print(Y)

[[4.600e-01 0.000e+00 0.000e+00 ... 2.000e+00 1.300e+01 8.600e+01]
 [0.000e+00 0.000e+00 0.000e+00 ... 2.829e+00 4.700e+01 1.160e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 1.500e+00 4.000e+00 3.000e+01]
 ...
 [0.000e+00 1.920e+00 0.000e+00 ... 2.750e+00 1.200e+01 3.300e+01]
 [1.900e-01 1.900e-01 2.900e-01 ... 4.295e+00 4.900e+01 8.720e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 1.312e+00 6.000e+00 6.300e+01]]
[0 0 0 ... 1 1 0]


In [38]:
x_train = X[:3300,:]
y_train = Y[:3300]
x_test = X[3300:,:]
y_test = Y[3300:]

In [32]:
x_train.shape

(3300, 57)

In [33]:
def print_metrics(Y_true, Y_predicted):
    print("Accuracy Score :" + str(accuracy_score(Y_true,Y_predicted)))
    print("Precision Score :" + str(precision_score(Y_true,Y_predicted)))
    print("Recall Score :" + str(recall_score(Y_true,Y_predicted)))
    print("ROC AUC Score :" + str(roc_auc_score(Y_true,Y_predicted)))
    print("Confusion Matrix : \n")
    print(confusion_matrix(Y_true,Y_predicted))

In [37]:
svm_clf = SVC(C=2000)
svm_clf.fit(x_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [3300, 1301]